using System.Collections.Generic;
using UnityEngine;
using Meridian.Geo;

namespace Meridian.Sim
{
    // INSTITUTIONS AND THE OVERRULE CYCLE — Consequence Engine §5, "the spine of the long game".
    //
    // An institution is the only thing in Meridian that BINDS THE PLAYER. Everything else the
    // player builds is a lever they hold; this is a lever they hand to someone else, and the
    // entire value of it comes from the fact that they cannot take it back cheaply.
    //
    //   times_overruled = 0  the institution's decisions carry real weight; members invest in it
    //   times_overruled = 1  it is treated as advisory; delegations withdraw; bloc-member
    //                        legitimacy drops sharply and accrual STOPS
    //   times_overruled = 2  it dissolves, and EVERY point of legitimacy it ever generated is
    //                        removed — not decayed, removed, exactly
    //
    // THE RESTORATION PLAY is meant to be the highest-value move available anywhere in the game:
    // break it, admit it publicly, rebuild it with MORE power than it had, submit to it — and end
    // up ahead of where you started. That is why Restore() forces Binding on (members demand
    // binding power as the price of coming back), pays an immediate public-admission dividend, and
    // multiplies the accrual rate. It is also why it costs the player standing with their own
    // military and their own population up front: you are publicly conceding that you were wrong.
    //
    // And the removal clause is the sharpest edge of all. An institution with one can vote the
    // player's government out. A leader who SURVIVES that vote is more legitimate afterwards than
    // one who never faced it — legitimacy you cannot buy, only risk.

    public enum InstitutionStatus { Active, Advisory, Dissolved }
    public enum RulingKind { CeaseWar, WithdrawCoercion, LowerTariff }
    public enum RulingOutcome { Pending, Complied, Overruled, Moot }

    public class Ruling
    {
        public RulingKind Kind;
        public int Against;              // the state the ruling binds — normally the founder
        public int Subject = -1;         // the other party, where the ruling is about one
        public long IssuedDay;
        public long DeadlineDay;
        public float Threshold;          // tariff cap / coercion cap, by kind
        public string Demand = "";
        public RulingOutcome Outcome = RulingOutcome.Pending;
        public string Resolution = "";
    }

    public class Institution
    {
        public string Name = "";
        public string HomeBloc = "";
        public int FoundedBy;
        public long FoundedDay;
        public bool Binding;             // do its rulings bind the founder, or merely advise?
        public bool HasRemovalClause;    // can it vote the founder's government out?
        public List<string> MemberIsos = new();

        public int TimesOverruled;
        public int TimesRestored;
        public InstitutionStatus Status = InstitutionStatus.Active;
        public long DissolvedDay = -1;

        // Per-observer legitimacy this institution has GENERATED by existing. Tracked exactly so
        // dissolution can remove exactly it — §5 says the accumulated legitimacy is lost, and a
        // decay approximation would quietly make dissolution survivable.
        public float[] Accrued = new float[ObserverExt.Count];

        public List<Ruling> Rulings = new();   // permanent, never pruned (Pillar 3)
        public bool RemovalVoteHeld;
        public bool SurvivedRemovalVote;
        public long RemovalVoteDay = -1;

        public bool IsAlive => Status != InstitutionStatus.Dissolved;
        public float AccrualRate => (Binding ? 2f : 1f) * (1f + 1.5f * TimesRestored);

        public int CompliedCount()
        {
            int n = 0;
            foreach (var r in Rulings) if (r.Outcome == RulingOutcome.Complied) n++;
            return n;
        }
        public Ruling PendingRuling()
        {
            foreach (var r in Rulings) if (r.Outcome == RulingOutcome.Pending) return r;
            return null;
        }
    }

    public class InstitutionSystem
    {
        public List<Institution> Institutions = new();

        public const float AccrualCapPerObserver = 25f;
        // A restored institution does not merely earn FASTER, it can earn MORE than the original
        // ever could. Without this the restoration play only ever draws level with the peak it
        // destroyed, and §5 is explicit that it has to be the highest-value move in the game.
        // The reason it works is not sentiment: the rebuilt body has binding power and a removal
        // clause the first one never had, so what it certifies about the founder is worth more.
        public static float AccrualCap(Institution inst) => AccrualCapPerObserver * (1f + inst.TimesRestored);
        public const long RulingWindowDays = 60;      // how long the founder has to comply
        public const long RulingIntervalDays = 45;    // minimum gap between rulings

        public Institution Find(string name)
        {
            foreach (var i in Institutions) if (i.Name == name) return i;
            return null;
        }
        public List<Institution> FoundedBy(int country)
        {
            var outp = new List<Institution>();
            foreach (var i in Institutions) if (i.FoundedBy == country) outp.Add(i);
            return outp;
        }

        // --- founding ---------------------------------------------------------------------

        public Institution Found(string name, string homeBloc, int by, long day, bool binding,
                                 bool removalClause, List<string> memberIsos,
                                 LegitimacySystem legit, GeoWorldNames names)
        {
            var inst = new Institution
            {
                Name = name, HomeBloc = homeBloc, FoundedBy = by, FoundedDay = day,
                Binding = binding, HasRemovalClause = removalClause,
                MemberIsos = memberIsos ?? new List<string>(),
            };
            Institutions.Add(inst);

            // Founding is a real trade, immediately: other states gain a reason to invest in you,
            // and your own army watches you tie your own hands. A binding institution costs more
            // with the military and is worth more with everyone else — that is the whole bargain.
            legit?.Record(by, day, "Founded " + name,
                binding
                    ? "Creating a body whose rulings bind you is the most expensive promise a state can make, and the only one anybody believes"
                    : "A body that advises but cannot bind is cheap to create and cheap to ignore, and everyone knows it",
                LegitimacySystem.Deltas(
                    blocMembers: binding ? 8f : 4f,
                    foreignGovernments: binding ? 7f : 3f,
                    foreignPopulations: binding ? 3f : 1f,
                    ownMilitary: binding ? -5f : -2f));
            return inst;
        }

        // --- the tick ----------------------------------------------------------------------

        public List<string> TickAll(long day, EconomySystem econ, NationalSystem nat, DiplomacySystem dip,
                                    LegitimacySystem legit, WarSystem wars, AccessionSystem accession,
                                    IReadOnlyList<Country> countries, GeoWorldNames names)
        {
            List<string> headlines = null;
            if (legit == null) return Empty;

            foreach (var inst in Institutions)
            {
                if (inst.Status == InstitutionStatus.Dissolved) continue;
                int f = inst.FoundedBy;
                if (f < 0 || f >= econ.States.Count) continue;

                // ACCRUAL — only while it is genuinely respected. The moment it is overruled once
                // and becomes advisory, it stops generating anything: nobody invests in a body the
                // founder has already ignored.
                if (inst.Status == InstitutionStatus.Active)
                {
                    Accrue(inst, f, Observer.BlocMembers, 0.020f * inst.AccrualRate, legit);
                    Accrue(inst, f, Observer.ForeignGovernments, 0.015f * inst.AccrualRate, legit);
                    Accrue(inst, f, Observer.ForeignPopulations, 0.008f * inst.AccrualRate, legit);
                }

                // RULINGS. An institution only rules when there is something to rule on, and only
                // against the founder — this is the machinery for binding the PLAYER, not for
                // giving them another way to bind other people.
                var pending = inst.PendingRuling();
                // An advisory body still rules — that is all an advisory body can do. Only its
                // ACCRUAL stopped. This is what makes the second overrule reachable at all, and
                // the ladder in §5 needs it: 0 -> advisory -> dissolved.
                if (pending == null && inst.IsAlive &&
                    day - LastRulingDay(inst) >= RulingIntervalDays)
                {
                    var issued = MaybeIssue(inst, day, econ, nat, dip, wars, accession, names);
                    if (issued != null)
                        (headlines ??= new List<string>()).Add(
                            $"{inst.Name} rules against {names?.Name(f)}: {issued.Demand} (by day {issued.DeadlineDay}).");
                }
                else if (pending != null && day >= pending.DeadlineDay)
                {
                    bool complied = Satisfied(pending, econ, nat, wars, accession);
                    if (complied) Comply(inst, pending, day, legit, names, ref headlines);
                    else Overrule(inst, pending, day, legit, names, ref headlines);
                }

                // REMOVAL VOTE. Only a binding institution with a removal clause can hold one, and
                // only when the founder is already in trouble at home. This is the one event in
                // the game where the player can gain legitimacy purely by risking everything.
                if (!inst.RemovalVoteHeld && inst.Binding && inst.HasRemovalClause &&
                    inst.Status == InstitutionStatus.Active &&
                    legit.Of(f).Get(Observer.OwnPopulation) < 30f)
                    HoldRemovalVote(inst, day, nat, legit, names, ref headlines);
            }
            return headlines ?? Empty;
        }

        void Accrue(Institution inst, int f, Observer o, float rate, LegitimacySystem legit)
        {
            float cap = AccrualCap(inst);
            if (inst.Accrued[(int)o] >= cap) return;
            float add = Mathf.Min(rate, cap - inst.Accrued[(int)o]);
            inst.Accrued[(int)o] += add;
            legit.Drift(f, o, add);
        }

        long LastRulingDay(Institution inst) =>
            inst.Rulings.Count == 0 ? inst.FoundedDay : inst.Rulings[inst.Rulings.Count - 1].IssuedDay;

        // --- issuing and testing rulings ---------------------------------------------------

        public Ruling MaybeIssue(Institution inst, long day, EconomySystem econ, NationalSystem nat,
                                 DiplomacySystem dip, WarSystem wars, AccessionSystem accession,
                                 GeoWorldNames names)
        {
            int f = inst.FoundedBy;

            // A war the founder started is the sharpest thing an institution can rule on.
            if (wars != null)
                foreach (var w in wars.WarsOf(f))
                    if (w.Attacker == f)
                        return Issue(inst, RulingKind.CeaseWar, day, w.Defender, 0f,
                            $"end the war against {names?.Name(w.Defender) ?? "the defender"}");

            // Pressure applied during an accession offer — §4's coercion, judged by a body the
            // founder created precisely so that somebody could judge it.
            if (accession != null)
                foreach (var inv in accession.Open)
                    if (inv.From == f && inv.ImpliedCoercion > 0.30f)
                        return Issue(inst, RulingKind.WithdrawCoercion, day, inv.To, 0.15f,
                            $"withdraw the pressure applied to {names?.Name(inv.To) ?? "the invited state"}");

            // The mundane one, and the one that will actually bite most often.
            if (econ.States[f].TaxTariff > 12f)
                return Issue(inst, RulingKind.LowerTariff, day, -1, 10f,
                    "lower tariffs to 10% or below");

            return null;
        }

        Ruling Issue(Institution inst, RulingKind kind, long day, int subject, float threshold, string demand)
        {
            var r = new Ruling
            {
                Kind = kind, Against = inst.FoundedBy, Subject = subject,
                IssuedDay = day, DeadlineDay = day + RulingWindowDays,
                Threshold = threshold, Demand = demand,
            };
            inst.Rulings.Add(r);
            return r;
        }

        // Compliance is measured against the WORLD, not against a button the player pressed. If
        // the war is over, they complied; if it is still running, they overruled — whatever they
        // said they intended.
        public bool Satisfied(Ruling r, EconomySystem econ, NationalSystem nat, WarSystem wars, AccessionSystem accession)
        {
            switch (r.Kind)
            {
                case RulingKind.CeaseWar:
                    return wars == null || wars.WarBetween(r.Against, r.Subject) == null;
                case RulingKind.WithdrawCoercion:
                    if (accession == null) return true;
                    foreach (var inv in accession.Open)
                        if (inv.From == r.Against && inv.To == r.Subject)
                            return inv.ImpliedCoercion <= r.Threshold;
                    return true;   // offer withdrawn or resolved: the pressure is gone either way
                case RulingKind.LowerTariff:
                    return econ.States[r.Against].TaxTariff <= r.Threshold;
            }
            return true;
        }

        // --- the ladder ---------------------------------------------------------------------

        void Comply(Institution inst, Ruling r, long day, LegitimacySystem legit, GeoWorldNames names,
                    ref List<string> headlines)
        {
            r.Outcome = RulingOutcome.Complied;
            r.Resolution = "complied";
            legit.Record(inst.FoundedBy, day, $"Complied with a ruling of {inst.Name}",
                "A state that obeys a body it could ignore is the only kind whose promises are worth anything",
                LegitimacySystem.Deltas(blocMembers: +5f, foreignGovernments: +4f,
                                        foreignPopulations: +2f, ownMilitary: -2f));
            (headlines ??= new List<string>()).Add(
                $"{names?.Name(inst.FoundedBy)} complies with {inst.Name} — {r.Demand}.");
        }

        public void Overrule(Institution inst, Ruling r, long day, LegitimacySystem legit, GeoWorldNames names,
                             ref List<string> headlines)
        {
            r.Outcome = RulingOutcome.Overruled;
            r.Resolution = "overruled";
            inst.TimesOverruled++;
            // Breaking a body you promised would bind you is worse the more power you had given it.
            float bite = 1f + 0.5f * inst.TimesRestored;

            if (inst.TimesOverruled == 1)
            {
                inst.Status = InstitutionStatus.Advisory;
                legit.Record(inst.FoundedBy, day, $"Overruled {inst.Name}",
                    "Delegations withdraw and the body becomes advisory; nobody invests in an institution its founder has already ignored once",
                    LegitimacySystem.Deltas(blocMembers: -18f * bite, foreignGovernments: -10f * bite,
                                            foreignPopulations: -5f * bite, ownPopulation: -4f));
                (headlines ??= new List<string>()).Add(
                    $"{names?.Name(inst.FoundedBy)} overrules {inst.Name}. It is advisory from today; delegations are withdrawing.");
            }
            else
            {
                Dissolve(inst, day, legit, names, ref headlines);
            }
        }

        public void Dissolve(Institution inst, long day, LegitimacySystem legit, GeoWorldNames names,
                             ref List<string> headlines)
        {
            inst.Status = InstitutionStatus.Dissolved;
            inst.DissolvedDay = day;

            // EXACTLY what it generated, removed. §5: "All legitimacy accumulated from its
            // existence is lost." Not decayed — lost. Everything those years of restraint bought.
            var give = new float[ObserverExt.Count];
            float total = 0f;
            for (int o = 0; o < ObserverExt.Count; o++)
            {
                give[o] = -inst.Accrued[o];
                total += inst.Accrued[o];
                inst.Accrued[o] = 0f;
            }
            give[(int)Observer.BlocMembers] -= 12f;
            give[(int)Observer.ForeignGovernments] -= 10f;
            give[(int)Observer.ReligiousAuthority] -= 5f;
            legit.Record(inst.FoundedBy, day, $"{inst.Name} dissolved after a second overrule",
                $"Every point of standing the institution earned over {(day - inst.FoundedDay) / 365}y is gone with it, and the years cannot be re-run",
                give);
            (headlines ??= new List<string>()).Add(
                $"{inst.Name} dissolves. {total:0} points of accumulated standing dissolve with it.");
        }

        // THE RESTORATION PLAY. §5: it must cost more than creating it did, members must demand
        // binding power as the price, and it must be worth doing anyway — the highest-value move
        // in the game for a player willing to admit publicly that they were wrong.
        public Institution Restore(Institution inst, long day, LegitimacySystem legit, GeoWorldNames names,
                                   ref List<string> headlines)
        {
            if (inst.Status != InstitutionStatus.Dissolved) return inst;

            inst.Status = InstitutionStatus.Active;
            inst.TimesOverruled = 0;
            inst.TimesRestored++;
            inst.Binding = true;              // non-negotiable: the members' price for coming back
            inst.HasRemovalClause = true;     // and they want the power to remove you, too
            inst.DissolvedDay = -1;

            legit.Record(inst.FoundedBy, day, $"Restored {inst.Name} with binding power",
                "Admitting publicly that you broke something, and then giving the rebuilt version power over you that it never had, is the most expensive and most convincing thing a state can do",
                LegitimacySystem.Deltas(
                    blocMembers: +12f, foreignGovernments: +10f, foreignPopulations: +8f,
                    ownPopulation: -5f,      // your own people watch you concede you were wrong
                    ownMilitary: -8f));      // your army watches you hand away a veto
            (headlines ??= new List<string>()).Add(
                $"{names?.Name(inst.FoundedBy)} restores {inst.Name} — binding this time, with a removal clause over the government that broke it.");
            return inst;
        }

        // A leader who survives a removal vote is more legitimate than one who never faced it.
        public bool HoldRemovalVote(Institution inst, long day, NationalSystem nat, LegitimacySystem legit,
                                    GeoWorldNames names, ref List<string> headlines)
        {
            inst.RemovalVoteHeld = true;
            inst.RemovalVoteDay = day;
            int f = inst.FoundedBy;
            var led = legit.Of(f);

            // The members decide on the record, not the mood: what you have done for this body,
            // and what the other governments in it think of you.
            float support = led.Get(Observer.BlocMembers) * 0.5f
                          + led.Get(Observer.ForeignGovernments) * 0.3f
                          + inst.CompliedCount() * 8f
                          - inst.TimesOverruled * 15f
                          // Having rebuilt the body with power over yourself is itself evidence,
                          // and it is the evidence that most weighs on a vote about whether you
                          // can be trusted with the office. Without this the removal clause only
                          // ever becomes live at the exact moment it is unsurvivable, and the
                          // player never gets to make the play the design is built around.
                          + inst.TimesRestored * 12f;
            bool survived = support >= 40f;
            inst.SurvivedRemovalVote = survived;

            if (survived)
            {
                legit.Record(f, day, $"Survived a removal vote in {inst.Name}",
                    "Submitting to a body that could have removed you, and not being removed, buys standing that cannot be bought any other way",
                    LegitimacySystem.Deltas(ownPopulation: +12f, foreignGovernments: +10f,
                                            blocMembers: +8f, foreignPopulations: +6f, ownMilitary: +6f));
                (headlines ??= new List<string>()).Add(
                    $"{names?.Name(f)} survives a removal vote in {inst.Name} with {support:0} support. It did not have to submit to the vote, and everyone knows it.");
            }
            else
            {
                if (f >= 0 && f < nat.States.Count)
                    nat.States[f].ApprovalRating = Mathf.Min(nat.States[f].ApprovalRating, 25f);
                legit.Record(f, day, $"Removed by a vote of {inst.Name}",
                    "Removed by the very body it created, under a clause it wrote itself",
                    LegitimacySystem.Deltas(ownPopulation: -12f, ownMilitary: -10f,
                                            foreignGovernments: -6f, blocMembers: -6f));
                (headlines ??= new List<string>()).Add(
                    $"{inst.Name} votes to remove the government of {names?.Name(f)} — with {support:0} support, under a clause it wrote itself.");
            }
            return survived;
        }

        static readonly List<string> Empty = new();
    }
}
